---
- name: setup directories
  file: path={{ home }}/{{ item }} state=directory
  with_items:
    - scripts
    - tmp
    - projects

- name: zsh facts
  shell: 'echo $SHELL'
  register: default_shell
  changed_when: False

- name: make zsh default
  shell: chsh -s /bin/zsh
  become_method: sudo
  when: default_shell.stdout.find('/bin/zsh') == -1


- name: download github repositories
  git: repo={{ item.url }}
       dest={{ item.dest }}
       update=no
       track_submodules=True
  vars:
      projects: "{{ home }}/projects/"
  with_items:
    - { url: 'git@github.com:JamshedVesuna/dotfiles.git', dest: "{{ home }}/scripts/dotfiles" }

- name: homebrew
  homebrew:
    state: present
    update_homebrew: yes
    upgrade_all: yes
    name:
      # Text Editors
      - macvim
      - vim
      # Languages
      - go
      - markdown
      - python
      - python3
      # Networking
      - curl
      - nmap
      - openssl
      - wget
      # Version Control
      - git
      # Virtual
      - docker
      - docker-machine
      - postgresql
      # Cli
      - bash
      - tmux
      - zsh
      # Searching
      - ack
      - the_silver_searcher
      # Misc tools
      - cask
      - cmake
      - ctags
      - gettext
      - gnupg2
      - gpg
      - grip

- name: homebrew cask
  homebrew_cask:
    name={{ item }}
    state=present
  with_items:
    - 1password
    - dropbox
    - google-chrome
    - slack
    - spectacle
    - spotify

- name: dotfile sourcing
  lineinfile: dest={{ home }}/{{ item.location }} line={{ item.line }} create=true
  with_items:
    - { location: '.bashrc',    line: 'export DOTFILES_PATH={{ home }}/scripts/dotfiles' }
    - { location: '.bashrc',    line: 'source $DOTFILES_PATH/bash/.bashrc' }
    - { location: '.zshrc',     line: 'export DOTFILES_PATH={{ home }}/scripts/dotfiles' }
    - { location: '.zshrc',     line: 'source $DOTFILES_PATH/zsh/.zshrc' }
    - { location: '.zshrc',     line: 'alias plax="cd ~/scripts/plax; ansible-playbook -i inventory playbook.yml; cd -"' }
    - { location: '.zshrc',     line: 'alias plaxe="mvim ~/scripts/plax/roles/system/tasks/main.yml"' }
    - { location: '.gvimrc',    line: 'source $DOTFILES_PATH/vim/.gvimrc' }
    - { location: '.tmux.conf', line: 'source $DOTFILES_PATH/tmux/.tmux.conf' }
    - { location: '.vimrc',     line: 'source $DOTFILES_PATH/vim/.vimrc' }
    - { location: '.gitconfig', line: '[include]' }
    - { location: '.gitconfig', line: '  path = ~/scripts/dotfiles/git/.gitconfig' }

- name: dotfile symlink
  file: src={{ home }}/scripts/dotfiles/vim/.vim dest={{ home }}/.vim state=link
