---
# TODO(jvesuna):
# Add Seil Capslock to Escape mapping (OS X >= 10.11)
#
# Updating:
# brew update; brew upgrade
# pip freeze --local | cut -d = -f 1 | xargs -n1 pip install -U

- name: setup directories
  file: path={{ home }}/{{ item }} state=directory
  with_items:
    - scripts
    - tmp

- name: zsh facts
  shell: 'echo $SHELL'
  register: default_shell
  changed_when: False

- name: make zsh default
  shell: chsh -s /bin/zsh
  become_method: sudo
  when: default_shell.stdout.find('/bin/zsh') == -1

- name: download dotfiles
  git: repo=https://github.com/altoduo/dotfiles.git
       dest={{ home }}/scripts/dotfiles
       update=no
       #track_submodules=True  # Supported by ansible >1.8

- name: homebrew install
  homebrew:
    name={{ item }}
    state=present
  with_items:
    # Text Editors
    - macvim
    - vim
    # Languages
    - go
    - markdown
    - python
    # Networking
    - curl
    - iperf
    - nmap
    - openssl
    - wget
    # Version Control
    - git
    - rdiff-backup
    # Cli
    - bash
    - tmux
    - zsh
    # Searching
    - ack
    - the_silver_searcher
    # Misc tools
    - awscli
    - brew-cask
    - cmake
    - ctags

- name: homebrew cask install
  homebrew_cask:
    name={{ item }}
    state=present
  with_items:
    - dropbox
    - google-chrome
    - keepassx
    - seil
    - slack
    - spectacle
    - spotify
    - vagrant
    - virtualbox

- name: pip install
  pip: name={{ item }}
  become_method: sudo
  with_items:
    - cronos
    - dropbox
    - grip
    - ipdb
    - ipython
    - joblib
    - line_profiler
    - numpy
    - pep8
    - virtualenv

- name: dotfile sourcing
  lineinfile: dest={{ home }}/{{ item.location }} line={{ item.line }} create=true
  with_items:
    - { location: '.bashrc ',      line: 'export DOTFILES_PATH={{ home }}/scripts/dotfiles' }
    - { location: '.bashrc ',      line: 'source \$DOTFILES_PATH/bash/.bashrc' }
    - { location: '.gvimrc',       line: 'source $DOTFILES_PATH/vim/.gvimrc' }
    - { location: '.tmux.conf',    line: 'source $DOTFILES_PATH/tmux/.tmux.conf' }
    - { location: '.vimrc',        line: 'source $DOTFILES_PATH/vim/.vimrc' }
    - { location: '.gitconfig',    line: '[include]' }
    - { location: '.gitconfig',    line: '  path = ~/scripts/dotfiles/git/.gitconfig' }

- name: dotfile symlink
  file: src={{ home }}/scripts/dotfiles/vim/.vim dest={{ home }}/.vim state=link
