---
- name: check if FileVault is enabled
  shell: fdesetup status
  register: filevault_status
  changed_when: false

- name: pause and prompt user if FileVault is not enabled
  pause:
    prompt: "FileVault is not enabled. Please enable it manually at System Preferences => Security & Privacy => FileVault and then press enter to continue"
  when: "'FileVault is Off' in filevault_status.stdout"

- name: homebrew
  homebrew:
    state: present
    update_homebrew: yes
    upgrade_all: yes
    name:
      # Text Editors
      - vim
      # Languages
      - go
      - markdown
      - npm
      - python
      # Networking
      - curl
      - nmap
      - openssl
      - wget
      # Version Control
      - git
      # Virtual
      - docker
      - docker-machine
      # Cli
      - bash
      - tmux
      - zsh
      # Searching
      - ack
      # Misc tools
      - cask
      - cmake
      - ctags
      - gcc
      - gettext
      - gnupg2
      - gpg
      - jq
      - terraform

- name: homebrew cask
  homebrew_cask:
    name={{ item }}
    state=present
    accept_external_apps=true
  with_items:
    - 1password
    - dropbox
    - google-chrome
    - google-cloud-sdk
    - google-drive
    - slack
    - zoom
